"""init schema

Revision ID: 9730ec3a47a9
Revises: 
Create Date: 2026-01-11 18:53:12.724882

"""
from alembic import op
import sqlalchemy as sa



revision = '9730ec3a47a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflict_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_raw', sa.String(length=50), nullable=False),
    sa.Column('country_norm', sa.String(length=50), nullable=False),
    sa.Column('admin1_raw', sa.String(length=50), nullable=False),
    sa.Column('admin1_norm', sa.String(length=50), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('events', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.CheckConstraint('events >= 0', name='ck_conflict_events_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_norm', 'admin1_norm', name='uq_conflict_country_admin1_norm')
    )
    op.create_index(op.f('ix_conflict_data_admin1_norm'), 'conflict_data', ['admin1_norm'], unique=False)
    op.create_index(op.f('ix_conflict_data_country_norm'), 'conflict_data', ['country_norm'], unique=False)
    op.create_table('risk_score_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_norm', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_norm', name='uq_risk_country_norm')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conflict_data_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conflict_data_id'], ['conflict_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('risk_score_cache')
    op.drop_index(op.f('ix_conflict_data_country_norm'), table_name='conflict_data')
    op.drop_index(op.f('ix_conflict_data_admin1_norm'), table_name='conflict_data')
    op.drop_table('conflict_data')
    # ### end Alembic commands ###
